ann_file = 'labels'
auto_scale_lr = dict(base_batch_size=2, enable=False)
backend_args = None
bda_aug_conf = dict(
    flip_dx_ratio=0.5,
    flip_dy_ratio=0.5,
    flip_dz_ratio=0.5,
    rot_lim=(
        0,
        0,
    ),
    scale_lim=(
        0.95,
        1.05,
    ))
camera_used = [
    'left',
]
class_names = [
    'unlabeled',
    'car',
    'bicycle',
    'motorcycle',
    'truck',
    'other-vehicle',
    'person',
    'bicyclist',
    'motorcyclist',
    'road',
    'parking',
    'sidewalk',
    'other-ground',
    'building',
    'fence',
    'vegetation',
    'trunk',
    'terrain',
    'pole',
    'traffic-sign',
]
custom_hooks = [
    dict(init_updates=10560, priority='NORMAL', type='MEGVIIEMAHook'),
]
custom_imports = dict(
    allow_failed_imports=False, imports=[
        'projects.SUGOcc.sugocc',
    ])
data_config = dict(
    crop_h=(
        0.0,
        0.0,
    ),
    flip=True,
    input_size=(
        384,
        1280,
    ),
    resize=(
        -0.06,
        0.11,
    ),
    resize_test=0.0,
    rot=(
        -5.4,
        5.4,
    ))
data_root = 'data/SemanticKITTI'
dataset_type = 'CustomSemanticKITTILssDataset'
default_hooks = dict(
    checkpoint=dict(interval=1, type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'))
embed_multi = dict(decay_mult=0.0, lr_mult=1.0)
find_unused_parameters = True
grid_config = dict(
    dbound=[
        2.0,
        58.0,
        0.5,
    ],
    xbound=[
        0,
        51.2,
        0.4,
    ],
    ybound=[
        -25.6,
        25.6,
        0.4,
    ],
    zbound=[
        -2,
        4.4,
        0.4,
    ])
img_norm_cfg = dict(
    mean=[
        123.675,
        116.28,
        103.53,
    ],
    std=[
        58.395,
        57.12,
        57.375,
    ],
    to_rgb=True)
input_modality = dict(
    use_camera=True,
    use_external=False,
    use_lidar=False,
    use_map=False,
    use_radar=False)
launcher = 'pytorch'
load_from = '/mnt/e/Projects/sugocc_kitti.pth'
log_processor = dict(window_size=50)
lss_downsample = [
    2,
    2,
    2,
]
lss_occ_size = [
    128,
    128,
    16,
]
mask2former_feat_channel = 80
mask2former_num_heads = 8
mask2former_num_queries = 100
mask2former_output_channel = 80
mask2former_pos_channel = 26.666666666666668
model = dict(
    img_backbone=dict(
        checkpoint_path='ckpts/maskdino_r50_50e_300q_panoptic_pq53.0.pth',
        config_path='maskdino/configs/maskdino_r50_8xb2-panoptic-export.py',
        custom_imports='maskdino',
        num_outs=4,
        type='MMDetWrapper'),
    img_bev_encoder_backbone=dict(
        cross_kernel=True,
        in_channels=[
            80,
            160,
            320,
            640,
        ],
        kernel_size=3,
        numC_input=80,
        num_blocks=[
            2,
            2,
            2,
            2,
        ],
        num_dense_blocks=3,
        out_channels=[
            80,
            80,
            80,
            80,
        ],
        type='MinkowskiUNetEncoder',
        voxel_size=[
            128,
            128,
            16,
        ]),
    img_bev_encoder_neck=dict(
        in_channels=[
            80,
            160,
            320,
            640,
        ],
        lss_downsample=[
            2,
            2,
            2,
        ],
        nclasses=20,
        out_channels=[
            80,
            160,
            320,
            640,
        ],
        process_block_num=[
            2,
            2,
            2,
        ],
        process_cross_kernel=True,
        process_kernel_size=3,
        pruning_ratio=[
            0.1,
            0.1,
            0.1,
        ],
        type='SparseGenerativePixelDecoder'),
    img_neck=dict(
        in_channels=[
            256,
            256,
            256,
            256,
            256,
        ],
        out_channels=[
            128,
            128,
            128,
            128,
            128,
        ],
        type='mmdet3d.SECONDFPN',
        upsample_strides=[
            0.25,
            0.5,
            1,
            2,
            4,
        ]),
    img_view_transformer=dict(
        cam_channels=33,
        data_config=dict(
            crop_h=(
                0.0,
                0.0,
            ),
            flip=True,
            input_size=(
                384,
                1280,
            ),
            resize=(
                -0.06,
                0.11,
            ),
            resize_test=0.0,
            rot=(
                -5.4,
                5.4,
            )),
        depth_pruning_ratio=0.1,
        downsample=16,
        grid_config=dict(
            dbound=[
                2.0,
                58.0,
                0.5,
            ],
            xbound=[
                0,
                51.2,
                0.4,
            ],
            ybound=[
                -25.6,
                25.6,
                0.4,
            ],
            zbound=[
                -2,
                4.4,
                0.4,
            ]),
        grid_size=[
            128,
            128,
            16,
        ],
        loss_depth_weight=1.0,
        lss_downsample=[
            2,
            2,
            2,
        ],
        numC_Trans=80,
        numC_input=640,
        num_classes=20,
        seg_pruning_ratio=0.1,
        type='ViewTransformerLiftSplatShootVoxel',
        vp_megvii=False),
    pts_bbox_head=dict(
        cascade_ratio=2,
        data_config=dict(
            crop_h=(
                0.0,
                0.0,
            ),
            flip=True,
            input_size=(
                384,
                1280,
            ),
            resize=(
                -0.06,
                0.11,
            ),
            resize_test=0.0,
            rot=(
                -5.4,
                5.4,
            )),
        dn_num=20,
        empty_idx=0,
        feat_channels=80,
        final_occ_size=[
            256,
            256,
            32,
        ],
        fine_topk=30000,
        grid_config=dict(
            dbound=[
                2.0,
                58.0,
                0.5,
            ],
            xbound=[
                0,
                51.2,
                0.4,
            ],
            ybound=[
                -25.6,
                25.6,
                0.4,
            ],
            zbound=[
                -2,
                4.4,
                0.4,
            ]),
        loss_cls=dict(
            class_weight=[
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                0.1,
            ],
            loss_weight=2.0,
            reduction='mean',
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=False),
        loss_dice=dict(
            activate=True,
            eps=1.0,
            loss_weight=5.0,
            naive_dice=True,
            reduction='mean',
            type='mmdet.DiceLoss',
            use_sigmoid=True),
        loss_mask=dict(
            loss_weight=5.0,
            reduction='mean',
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=True),
        num_occupancy_classes=20,
        num_queries=100,
        out_channels=80,
        point_cloud_range=[
            0,
            -25.6,
            -2,
            51.2,
            25.6,
            4.4,
        ],
        pooling_attn_mask=True,
        positional_encoding=dict(
            normalize=True,
            num_feats=26.666666666666668,
            type='SinePositionalEncoding3D'),
        sample_from_img=False,
        sample_from_voxel=True,
        sample_weight_gamma=0.25,
        sparse_input=True,
        transformer_decoder=dict(
            init_cfg=None,
            num_layers=1,
            return_intermediate=True,
            transformerlayers=dict(
                attn_cfgs=dict(
                    attn_drop=0.1,
                    batch_first=False,
                    dropout_layer=None,
                    embed_dims=80,
                    num_heads=8,
                    proj_drop=0.0,
                    type='MultiheadAttention'),
                feedforward_channels=640,
                ffn_cfgs=dict(
                    act_cfg=dict(inplace=True, type='ReLU'),
                    add_identity=True,
                    dropout_layer=None,
                    embed_dims=80,
                    feedforward_channels=640,
                    ffn_drop=0.1,
                    num_fcs=2),
                operation_order=(
                    'cross_attn',
                    'norm',
                    'self_attn',
                    'norm',
                    'ffn',
                    'norm',
                ),
                type='DetrTransformerDecoderLayer'),
            type='DetrTransformerDecoder'),
        type='SparseOCRMask2OccHead'),
    test_cfg=dict(
        pts=dict(instance_on=False, panoptic_on=False, semantic_on=True)),
    train_cfg=dict(
        pts=dict(
            assigner=dict(
                cls_cost=dict(type='ClassificationCost', weight=2.0),
                dice_cost=dict(
                    eps=1.0, pred_act=True, type='DiceCost', weight=5.0),
                mask_cost=dict(
                    type='CrossEntropyLossCost', use_sigmoid=True, weight=5.0),
                type='MaskHungarianAssigner'),
            importance_sample_ratio=0.75,
            num_points=50176,
            oversample_ratio=3.0,
            sampler=dict(type='MaskPseudoSampler'))),
    type='SUGOcc')
norm_cfg = dict(num_groups=32, requires_grad=True, type='GN')
numC_Trans = 80
num_class = 20
occ_size = [
    256,
    256,
    32,
]
optim_wrapper = dict(
    clip_grad=dict(max_norm=35, norm_type=2),
    optimizer=dict(
        betas=(
            0.9,
            0.999,
        ),
        eps=1e-08,
        lr=0.0004,
        type='AdamW',
        weight_decay=0.01),
    paramwise_cfg=dict(
        custom_keys=dict(
            absolute_pos_embed=dict(decay_mult=0.0),
            img_backbone=dict(decay_mult=1.0, lr_mult=0.1),
            level_embed=dict(decay_mult=0.0, lr_mult=1.0),
            query_embed=dict(decay_mult=0.0, lr_mult=1.0),
            query_feat=dict(decay_mult=0.0, lr_mult=1.0),
            relative_position_bias_table=dict(decay_mult=0.0)),
        norm_decay_mult=0.0),
    type='OptimWrapper')
param_scheduler = dict(
    by_epoch=True, gamma=0.1, milestones=[
        20,
        25,
    ], type='MultiStepLR')
point_cloud_range = [
    0,
    -25.6,
    -2,
    51.2,
    25.6,
    4.4,
]
randomness = dict(seed=0)
sync_bn = 'torch'
test_cfg = dict()
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='labels',
        camera_used=[
            'left',
        ],
        classes=[
            'unlabeled',
            'car',
            'bicycle',
            'motorcycle',
            'truck',
            'other-vehicle',
            'person',
            'bicyclist',
            'motorcyclist',
            'road',
            'parking',
            'sidewalk',
            'other-ground',
            'building',
            'fence',
            'vegetation',
            'trunk',
            'terrain',
            'pole',
            'traffic-sign',
        ],
        data_root='data/SemanticKITTI',
        modality=dict(
            use_camera=True,
            use_external=False,
            use_lidar=False,
            use_map=False,
            use_radar=False),
        occ_size=[
            256,
            256,
            32,
        ],
        pc_range=[
            0,
            -25.6,
            -2,
            51.2,
            25.6,
            4.4,
        ],
        pipeline=[
            dict(
                data_config=dict(
                    crop_h=(
                        0.0,
                        0.0,
                    ),
                    flip=True,
                    input_size=(
                        384,
                        1280,
                    ),
                    resize=(
                        -0.06,
                        0.11,
                    ),
                    resize_test=0.0,
                    rot=(
                        -5.4,
                        5.4,
                    )),
                data_root='data/SemanticKITTI',
                img_norm_cfg=dict(
                    mean=[
                        123.675,
                        116.28,
                        103.53,
                    ],
                    std=[
                        58.395,
                        57.12,
                        57.375,
                    ],
                    to_rgb=True),
                is_train=False,
                type='LoadMultiViewImageFromFiles_SemanticKitti'),
            dict(
                bda_aug_conf=dict(
                    flip_dx_ratio=0.5,
                    flip_dy_ratio=0.5,
                    flip_dz_ratio=0.5,
                    rot_lim=(
                        0,
                        0,
                    ),
                    scale_lim=(
                        0.95,
                        1.05,
                    )),
                is_train=False,
                point_cloud_range=[
                    0,
                    -25.6,
                    -2,
                    51.2,
                    25.6,
                    4.4,
                ],
                type='LoadSemKittiAnnotation'),
            dict(type='OccDefaultFormatBundle3D'),
            dict(
                keys=[
                    'img_inputs',
                    'gt_occ',
                ],
                meta_keys=[
                    'pc_range',
                    'occ_size',
                    'lidar2img',
                    'cam_intrinsic',
                    'sequence',
                    'frame_id',
                    'raw_img',
                ],
                type='CustomPack3DDetInputs'),
        ],
        split='test',
        test_mode=True,
        type='CustomSemanticKITTILssDataset'),
    drop_last=False,
    num_workers=8,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(type='CustomOccMetric')
test_pipeline = [
    dict(
        data_config=dict(
            crop_h=(
                0.0,
                0.0,
            ),
            flip=True,
            input_size=(
                384,
                1280,
            ),
            resize=(
                -0.06,
                0.11,
            ),
            resize_test=0.0,
            rot=(
                -5.4,
                5.4,
            )),
        data_root='data/SemanticKITTI',
        img_norm_cfg=dict(
            mean=[
                123.675,
                116.28,
                103.53,
            ],
            std=[
                58.395,
                57.12,
                57.375,
            ],
            to_rgb=True),
        is_train=False,
        type='LoadMultiViewImageFromFiles_SemanticKitti'),
    dict(
        bda_aug_conf=dict(
            flip_dx_ratio=0.5,
            flip_dy_ratio=0.5,
            flip_dz_ratio=0.5,
            rot_lim=(
                0,
                0,
            ),
            scale_lim=(
                0.95,
                1.05,
            )),
        is_train=False,
        point_cloud_range=[
            0,
            -25.6,
            -2,
            51.2,
            25.6,
            4.4,
        ],
        type='LoadSemKittiAnnotation'),
    dict(type='OccDefaultFormatBundle3D'),
    dict(
        keys=[
            'img_inputs',
            'gt_occ',
        ],
        meta_keys=[
            'pc_range',
            'occ_size',
            'lidar2img',
            'cam_intrinsic',
            'sequence',
            'frame_id',
            'raw_img',
        ],
        type='CustomPack3DDetInputs'),
]
train_cfg = dict(by_epoch=True, max_epochs=20, val_interval=1)
train_dataloader = dict(
    batch_size=2,
    dataset=dict(
        ann_file='labels',
        camera_used=[
            'left',
        ],
        classes=[
            'unlabeled',
            'car',
            'bicycle',
            'motorcycle',
            'truck',
            'other-vehicle',
            'person',
            'bicyclist',
            'motorcyclist',
            'road',
            'parking',
            'sidewalk',
            'other-ground',
            'building',
            'fence',
            'vegetation',
            'trunk',
            'terrain',
            'pole',
            'traffic-sign',
        ],
        data_root='data/SemanticKITTI',
        modality=dict(
            use_camera=True,
            use_external=False,
            use_lidar=False,
            use_map=False,
            use_radar=False),
        occ_size=[
            256,
            256,
            32,
        ],
        pc_range=[
            0,
            -25.6,
            -2,
            51.2,
            25.6,
            4.4,
        ],
        pipeline=[
            dict(
                data_config=dict(
                    crop_h=(
                        0.0,
                        0.0,
                    ),
                    flip=True,
                    input_size=(
                        384,
                        1280,
                    ),
                    resize=(
                        -0.06,
                        0.11,
                    ),
                    resize_test=0.0,
                    rot=(
                        -5.4,
                        5.4,
                    )),
                data_root='data/SemanticKITTI',
                img_norm_cfg=dict(
                    mean=[
                        123.675,
                        116.28,
                        103.53,
                    ],
                    std=[
                        58.395,
                        57.12,
                        57.375,
                    ],
                    to_rgb=True),
                is_train=True,
                type='LoadMultiViewImageFromFiles_SemanticKitti'),
            dict(
                data_root='data/SemanticKITTI',
                dataset='kitti',
                type='CreateDepthFromLiDAR'),
            dict(
                bda_aug_conf=dict(
                    flip_dx_ratio=0.5,
                    flip_dy_ratio=0.5,
                    flip_dz_ratio=0.5,
                    rot_lim=(
                        0,
                        0,
                    ),
                    scale_lim=(
                        0.95,
                        1.05,
                    )),
                is_train=True,
                point_cloud_range=[
                    0,
                    -25.6,
                    -2,
                    51.2,
                    25.6,
                    4.4,
                ],
                type='LoadSemKittiAnnotation'),
            dict(type='OccDefaultFormatBundle3D'),
            dict(
                keys=[
                    'img_inputs',
                    'gt_occ',
                ],
                meta_keys=[
                    'pc_range',
                    'occ_size',
                    'lidar2img',
                    'cam_intrinsic',
                ],
                type='CustomPack3DDetInputs'),
        ],
        split='train',
        test_mode=False,
        type='CustomSemanticKITTILssDataset'),
    num_workers=8,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(
        data_config=dict(
            crop_h=(
                0.0,
                0.0,
            ),
            flip=True,
            input_size=(
                384,
                1280,
            ),
            resize=(
                -0.06,
                0.11,
            ),
            resize_test=0.0,
            rot=(
                -5.4,
                5.4,
            )),
        data_root='data/SemanticKITTI',
        img_norm_cfg=dict(
            mean=[
                123.675,
                116.28,
                103.53,
            ],
            std=[
                58.395,
                57.12,
                57.375,
            ],
            to_rgb=True),
        is_train=True,
        type='LoadMultiViewImageFromFiles_SemanticKitti'),
    dict(
        data_root='data/SemanticKITTI',
        dataset='kitti',
        type='CreateDepthFromLiDAR'),
    dict(
        bda_aug_conf=dict(
            flip_dx_ratio=0.5,
            flip_dy_ratio=0.5,
            flip_dz_ratio=0.5,
            rot_lim=(
                0,
                0,
            ),
            scale_lim=(
                0.95,
                1.05,
            )),
        is_train=True,
        point_cloud_range=[
            0,
            -25.6,
            -2,
            51.2,
            25.6,
            4.4,
        ],
        type='LoadSemKittiAnnotation'),
    dict(type='OccDefaultFormatBundle3D'),
    dict(
        keys=[
            'img_inputs',
            'gt_occ',
        ],
        meta_keys=[
            'pc_range',
            'occ_size',
            'lidar2img',
            'cam_intrinsic',
        ],
        type='CustomPack3DDetInputs'),
]
val_cfg = dict()
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='labels',
        camera_used=[
            'left',
        ],
        classes=[
            'unlabeled',
            'car',
            'bicycle',
            'motorcycle',
            'truck',
            'other-vehicle',
            'person',
            'bicyclist',
            'motorcyclist',
            'road',
            'parking',
            'sidewalk',
            'other-ground',
            'building',
            'fence',
            'vegetation',
            'trunk',
            'terrain',
            'pole',
            'traffic-sign',
        ],
        data_root='data/SemanticKITTI',
        modality=dict(
            use_camera=True,
            use_external=False,
            use_lidar=False,
            use_map=False,
            use_radar=False),
        occ_size=[
            256,
            256,
            32,
        ],
        pc_range=[
            0,
            -25.6,
            -2,
            51.2,
            25.6,
            4.4,
        ],
        pipeline=[
            dict(
                data_config=dict(
                    crop_h=(
                        0.0,
                        0.0,
                    ),
                    flip=True,
                    input_size=(
                        384,
                        1280,
                    ),
                    resize=(
                        -0.06,
                        0.11,
                    ),
                    resize_test=0.0,
                    rot=(
                        -5.4,
                        5.4,
                    )),
                data_root='data/SemanticKITTI',
                img_norm_cfg=dict(
                    mean=[
                        123.675,
                        116.28,
                        103.53,
                    ],
                    std=[
                        58.395,
                        57.12,
                        57.375,
                    ],
                    to_rgb=True),
                is_train=False,
                type='LoadMultiViewImageFromFiles_SemanticKitti'),
            dict(
                bda_aug_conf=dict(
                    flip_dx_ratio=0.5,
                    flip_dy_ratio=0.5,
                    flip_dz_ratio=0.5,
                    rot_lim=(
                        0,
                        0,
                    ),
                    scale_lim=(
                        0.95,
                        1.05,
                    )),
                is_train=False,
                point_cloud_range=[
                    0,
                    -25.6,
                    -2,
                    51.2,
                    25.6,
                    4.4,
                ],
                type='LoadSemKittiAnnotation'),
            dict(type='OccDefaultFormatBundle3D'),
            dict(
                keys=[
                    'img_inputs',
                    'gt_occ',
                ],
                meta_keys=[
                    'pc_range',
                    'occ_size',
                    'lidar2img',
                    'cam_intrinsic',
                    'sequence',
                    'frame_id',
                    'raw_img',
                ],
                type='CustomPack3DDetInputs'),
        ],
        split='test',
        test_mode=True,
        type='CustomSemanticKITTILssDataset'),
    drop_last=False,
    num_workers=8,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(type='CustomOccMetric')
voxel_channels = [
    80,
    160,
    320,
    640,
]
voxel_out_channels = 80
voxel_size = [
    0.2,
    0.2,
    0.2,
]
voxel_x = 0.2
voxel_y = 0.2
voxel_z = 0.2
work_dir = './work_dirs/sugocc_kitti'
