ann_file = 'labels'
auto_scale_lr = dict(base_batch_size=2, enable=False)
backend_args = None
bda_aug_conf = dict(
    flip_dx_ratio=0.5,
    flip_dy_ratio=0.5,
    rot_lim=(
        0,
        0,
    ),
    scale_lim=(
        1.0,
        1.0,
    ))
camera_used = [
    'left',
]
class_names = [
    'others',
    'barrier',
    'bicycle',
    'bus',
    'car',
    'construction_vehicle',
    'motorcycle',
    'pedestrian',
    'traffic_cone',
    'trailer',
    'truck',
    'driveable_surface',
    'other_flat',
    'sidewalk',
    'terrain',
    'manmade',
    'vegetation',
    'free',
]
custom_hooks = [
    dict(init_updates=10560, priority='NORMAL', type='MEGVIIEMAHook'),
]
custom_imports = dict(
    allow_failed_imports=False, imports=[
        'projects.SUGOcc.sugocc',
    ])
data_config = dict(
    Ncams=6,
    cams=[
        'CAM_FRONT_LEFT',
        'CAM_FRONT',
        'CAM_FRONT_RIGHT',
        'CAM_BACK_LEFT',
        'CAM_BACK',
        'CAM_BACK_RIGHT',
    ],
    crop_h=(
        0.0,
        0.0,
    ),
    flip=True,
    input_size=(
        256,
        704,
    ),
    resize=(
        -0.06,
        0.11,
    ),
    resize_test=0.0,
    rot=(
        -5.4,
        5.4,
    ),
    src_size=(
        900,
        1600,
    ))
data_root = 'data/nuscenes/'
dataset_type = 'CustomNuScenesDatasetOccupancy'
default_hooks = dict(
    checkpoint=dict(interval=1, type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'))
embed_multi = dict(decay_mult=0.0, lr_mult=1.0)
file_client_args = dict(backend='disk')
grid_config = dict(
    dbound=[
        1.0,
        45.0,
        0.5,
    ],
    xbound=[
        -40,
        40,
        0.4,
    ],
    ybound=[
        -40,
        40,
        0.4,
    ],
    zbound=[
        -1,
        5.4,
        0.4,
    ])
img_norm_cfg = dict(
    mean=[
        123.675,
        116.28,
        103.53,
    ],
    std=[
        58.395,
        57.12,
        57.375,
    ],
    to_rgb=True)
input_modality = dict(
    use_camera=True,
    use_external=False,
    use_lidar=False,
    use_map=False,
    use_radar=False)
launcher = 'pytorch'
load_from = '/mnt/e/Projects/sugocc_womask_miou3156.pth'
log_processor = dict(window_size=50)
lss_downsample = [
    1,
    1,
    1,
]
lss_occ_size = [
    200,
    200,
    16,
]
mask2former_feat_channel = 48
mask2former_num_heads = 8
mask2former_num_queries = 108
mask2former_output_channel = 48
mask2former_pos_channel = 16.0
model = dict(
    dataset='nuscenes',
    img_backbone=dict(
        depth=50,
        frozen_stages=-1,
        norm_cfg=dict(requires_grad=True, type='BN'),
        norm_eval=False,
        num_stages=4,
        out_indices=(
            0,
            2,
            3,
        ),
        style='pytorch',
        type='mmdet.ResNet',
        with_cp=True),
    img_bev_encoder_backbone=dict(
        cross_kernel=True,
        dense_kernels=[
            (
                7,
                7,
                3,
            ),
            (
                11,
                11,
                3,
            ),
            (
                21,
                21,
                3,
            ),
        ],
        in_channels=[
            48,
            96,
            192,
            384,
        ],
        kernel_size=3,
        numC_input=80,
        num_blocks=[
            2,
            2,
            2,
            2,
        ],
        num_dense_blocks=3,
        out_channels=[
            48,
            96,
            192,
            384,
        ],
        type='MinkowskiUNetEncoder',
        voxel_size=[
            200,
            200,
            16,
        ]),
    img_bev_encoder_neck=dict(
        dataset='nuscenes',
        empty_idx=17,
        in_channels=[
            48,
            96,
            192,
            384,
        ],
        lss_downsample=[
            1,
            1,
            1,
        ],
        nclasses=18,
        out_channels=[
            48,
            96,
            192,
            384,
        ],
        process_block_num=[
            2,
            2,
            2,
        ],
        process_cross_kernel=True,
        process_kernel_size=3,
        pruning_ratio=[
            0.1,
            0.1,
            0.1,
        ],
        type='SparseGenerativePixelDecoder',
        voxel_range=[
            200,
            200,
            16,
        ],
        wo_mask=True),
    img_neck=dict(
        in_channels=[
            1024,
            2048,
        ],
        num_outs=1,
        out_channels=512,
        out_ids=[
            0,
        ],
        start_level=0,
        type='CustomFPN',
        with_cp=True),
    img_view_transformer=dict(
        cam_channels=27,
        data_config=dict(
            Ncams=6,
            cams=[
                'CAM_FRONT_LEFT',
                'CAM_FRONT',
                'CAM_FRONT_RIGHT',
                'CAM_BACK_LEFT',
                'CAM_BACK',
                'CAM_BACK_RIGHT',
            ],
            crop_h=(
                0.0,
                0.0,
            ),
            flip=True,
            input_size=(
                256,
                704,
            ),
            resize=(
                -0.06,
                0.11,
            ),
            resize_test=0.0,
            rot=(
                -5.4,
                5.4,
            ),
            src_size=(
                900,
                1600,
            )),
        dataset='nuscenes',
        depth_pruning_ratio=0.1,
        depthnet_cfg=dict(aspp_mid_channels=96, use_dcn=False),
        downsample=16,
        empty_idx=17,
        grid_config=dict(
            dbound=[
                1.0,
                45.0,
                0.5,
            ],
            xbound=[
                -40,
                40,
                0.4,
            ],
            ybound=[
                -40,
                40,
                0.4,
            ],
            zbound=[
                -1,
                5.4,
                0.4,
            ]),
        grid_size=[
            200,
            200,
            16,
        ],
        loss_depth_weight=3.0,
        lss_downsample=[
            1,
            1,
            1,
        ],
        numC_Trans=80,
        numC_input=512,
        num_cam=1,
        num_classes=18,
        seg_pruning_ratio=0.1,
        type='ViewTransformerLiftSplatShootVoxel',
        vp_megvii=False),
    pts_bbox_head=dict(
        cascade_ratio=2,
        data_config=dict(
            Ncams=6,
            cams=[
                'CAM_FRONT_LEFT',
                'CAM_FRONT',
                'CAM_FRONT_RIGHT',
                'CAM_BACK_LEFT',
                'CAM_BACK',
                'CAM_BACK_RIGHT',
            ],
            crop_h=(
                0.0,
                0.0,
            ),
            flip=True,
            input_size=(
                256,
                704,
            ),
            resize=(
                -0.06,
                0.11,
            ),
            resize_test=0.0,
            rot=(
                -5.4,
                5.4,
            ),
            src_size=(
                900,
                1600,
            )),
        dataset='nuscenes',
        dn_num=18,
        empty_idx=17,
        feat_channels=48,
        final_occ_size=[
            200,
            200,
            16,
        ],
        fine_topk=30000,
        grid_config=dict(
            dbound=[
                1.0,
                45.0,
                0.5,
            ],
            xbound=[
                -40,
                40,
                0.4,
            ],
            ybound=[
                -40,
                40,
                0.4,
            ],
            zbound=[
                -1,
                5.4,
                0.4,
            ]),
        loss_cls=dict(
            class_weight=[
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                0.1,
            ],
            loss_weight=2.0,
            reduction='mean',
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=False),
        loss_dice=dict(
            activate=True,
            eps=1.0,
            loss_weight=5.0,
            naive_dice=True,
            reduction='mean',
            type='mmdet.DiceLoss',
            use_sigmoid=True),
        loss_mask=dict(
            loss_weight=5.0,
            reduction='mean',
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=True),
        lss_downsample=[
            1,
            1,
            1,
        ],
        norm_cfg=dict(num_groups=24, requires_grad=True, type='GN'),
        num_occupancy_classes=18,
        num_queries=108,
        out_channels=48,
        point_cloud_range=[
            -40.0,
            -40.0,
            -1,
            40.0,
            40.0,
            5.4,
        ],
        pooling_attn_mask=True,
        positional_encoding=dict(
            normalize=True, num_feats=16.0, type='SinePositionalEncoding3D'),
        sample_from_img=False,
        sample_from_voxel=True,
        sample_weight_gamma=0.25,
        sparse_input=True,
        transformer_decoder=dict(
            init_cfg=None,
            num_layers=1,
            return_intermediate=True,
            transformerlayers=dict(
                attn_cfgs=dict(
                    attn_drop=0.1,
                    batch_first=False,
                    dropout_layer=None,
                    embed_dims=48,
                    num_heads=8,
                    proj_drop=0.0,
                    type='MultiheadAttention'),
                feedforward_channels=384,
                ffn_cfgs=dict(
                    act_cfg=dict(inplace=True, type='ReLU'),
                    add_identity=True,
                    dropout_layer=None,
                    embed_dims=48,
                    feedforward_channels=384,
                    ffn_drop=0.1,
                    num_fcs=2),
                operation_order=(
                    'cross_attn',
                    'norm',
                    'self_attn',
                    'norm',
                    'ffn',
                    'norm',
                ),
                type='DetrTransformerDecoderLayer'),
            type='DetrTransformerDecoder'),
        type='SparseOCRMask2OccHead',
        wo_mask=True),
    test_cfg=dict(
        pts=dict(instance_on=False, panoptic_on=False, semantic_on=True)),
    train_cfg=dict(
        pts=dict(
            assigner=dict(
                cls_cost=dict(type='ClassificationCost', weight=2.0),
                dice_cost=dict(
                    eps=1.0, pred_act=True, type='DiceCost', weight=5.0),
                mask_cost=dict(
                    type='CrossEntropyLossCost', use_sigmoid=True, weight=5.0),
                type='MaskHungarianAssigner'),
            importance_sample_ratio=0.75,
            num_points=25088,
            oversample_ratio=3.0,
            sampler=dict(type='MaskPseudoSampler'))),
    type='SUGOcc')
norm_cfg = dict(num_groups=24, requires_grad=True, type='GN')
not_use_mask = True
numC_Trans = 80
num_class = 18
occ_size = [
    200,
    200,
    16,
]
optim_wrapper = dict(
    clip_grad=dict(max_norm=5, norm_type=2),
    optimizer=dict(lr=0.0004, type='AdamW', weight_decay=0.01),
    type='OptimWrapper')
param_scheduler = [
    dict(by_epoch=True, gamma=0.1, milestones=[
        100,
    ], type='MultiStepLR'),
    dict(by_epoch=False, end=200, start_factor=0.001, type='LinearLR'),
]
point_cloud_range = [
    -40.0,
    -40.0,
    -1,
    40.0,
    40.0,
    5.4,
]
randomness = dict(seed=0)
sync_bn = 'torch'
test_cfg = dict()
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='bevdetv2-nuscenes_infos_val.pkl',
        classes=[
            'others',
            'barrier',
            'bicycle',
            'bus',
            'car',
            'construction_vehicle',
            'motorcycle',
            'pedestrian',
            'traffic_cone',
            'trailer',
            'truck',
            'driveable_surface',
            'other_flat',
            'sidewalk',
            'terrain',
            'manmade',
            'vegetation',
            'free',
        ],
        data_root='data/nuscenes/',
        filter_empty_gt=False,
        img_info_prototype='bevdet',
        modality=dict(
            use_camera=True,
            use_external=False,
            use_lidar=False,
            use_map=False,
            use_radar=False),
        occ_size=[
            200,
            200,
            16,
        ],
        pc_range=[
            -40.0,
            -40.0,
            -1,
            40.0,
            40.0,
            5.4,
        ],
        pipeline=[
            dict(
                data_config=dict(
                    Ncams=6,
                    cams=[
                        'CAM_FRONT_LEFT',
                        'CAM_FRONT',
                        'CAM_FRONT_RIGHT',
                        'CAM_BACK_LEFT',
                        'CAM_BACK',
                        'CAM_BACK_RIGHT',
                    ],
                    crop_h=(
                        0.0,
                        0.0,
                    ),
                    flip=True,
                    input_size=(
                        256,
                        704,
                    ),
                    resize=(
                        -0.06,
                        0.11,
                    ),
                    resize_test=0.0,
                    rot=(
                        -5.4,
                        5.4,
                    ),
                    src_size=(
                        900,
                        1600,
                    )),
                sequential=False,
                type='PrepareImageInputs'),
            dict(
                bda_aug_conf=dict(
                    flip_dx_ratio=0.5,
                    flip_dy_ratio=0.5,
                    rot_lim=(
                        0,
                        0,
                    ),
                    scale_lim=(
                        1.0,
                        1.0,
                    )),
                classes=[
                    'others',
                    'barrier',
                    'bicycle',
                    'bus',
                    'car',
                    'construction_vehicle',
                    'motorcycle',
                    'pedestrian',
                    'traffic_cone',
                    'trailer',
                    'truck',
                    'driveable_surface',
                    'other_flat',
                    'sidewalk',
                    'terrain',
                    'manmade',
                    'vegetation',
                    'free',
                ],
                is_train=False,
                type='LoadAnnotationsBEVDepth'),
            dict(
                coord_type='LIDAR',
                load_dim=5,
                type='mmdet3d.LoadPointsFromFile',
                use_dim=5),
            dict(type='OccDefaultFormatBundle3D'),
            dict(
                keys=[
                    'img_inputs',
                ],
                meta_keys=[
                    'pc_range',
                    'occ_size',
                    'sample_idx',
                    'filename',
                ],
                type='CustomPack3DDetInputs'),
        ],
        test_mode=True,
        type='CustomNuScenesDatasetOccupancy'),
    num_workers=8,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(type='CustomOccMetricNuscenes')
test_pipeline = [
    dict(
        data_config=dict(
            Ncams=6,
            cams=[
                'CAM_FRONT_LEFT',
                'CAM_FRONT',
                'CAM_FRONT_RIGHT',
                'CAM_BACK_LEFT',
                'CAM_BACK',
                'CAM_BACK_RIGHT',
            ],
            crop_h=(
                0.0,
                0.0,
            ),
            flip=True,
            input_size=(
                256,
                704,
            ),
            resize=(
                -0.06,
                0.11,
            ),
            resize_test=0.0,
            rot=(
                -5.4,
                5.4,
            ),
            src_size=(
                900,
                1600,
            )),
        sequential=False,
        type='PrepareImageInputs'),
    dict(
        bda_aug_conf=dict(
            flip_dx_ratio=0.5,
            flip_dy_ratio=0.5,
            rot_lim=(
                0,
                0,
            ),
            scale_lim=(
                1.0,
                1.0,
            )),
        classes=[
            'others',
            'barrier',
            'bicycle',
            'bus',
            'car',
            'construction_vehicle',
            'motorcycle',
            'pedestrian',
            'traffic_cone',
            'trailer',
            'truck',
            'driveable_surface',
            'other_flat',
            'sidewalk',
            'terrain',
            'manmade',
            'vegetation',
            'free',
        ],
        is_train=False,
        type='LoadAnnotationsBEVDepth'),
    dict(
        coord_type='LIDAR',
        load_dim=5,
        type='mmdet3d.LoadPointsFromFile',
        use_dim=5),
    dict(type='OccDefaultFormatBundle3D'),
    dict(
        keys=[
            'img_inputs',
        ],
        meta_keys=[
            'pc_range',
            'occ_size',
            'sample_idx',
            'filename',
        ],
        type='CustomPack3DDetInputs'),
]
train_cfg = dict(by_epoch=True, max_epochs=100, val_interval=1)
train_dataloader = dict(
    batch_size=2,
    dataset=dict(
        ann_file='bevdetv2-nuscenes_infos_train.pkl',
        classes=[
            'others',
            'barrier',
            'bicycle',
            'bus',
            'car',
            'construction_vehicle',
            'motorcycle',
            'pedestrian',
            'traffic_cone',
            'trailer',
            'truck',
            'driveable_surface',
            'other_flat',
            'sidewalk',
            'terrain',
            'manmade',
            'vegetation',
            'free',
        ],
        data_root='data/nuscenes/',
        filter_empty_gt=False,
        img_info_prototype='bevdet',
        modality=dict(
            use_camera=True,
            use_external=False,
            use_lidar=False,
            use_map=False,
            use_radar=False),
        occ_size=[
            200,
            200,
            16,
        ],
        pc_range=[
            -40.0,
            -40.0,
            -1,
            40.0,
            40.0,
            5.4,
        ],
        pipeline=[
            dict(
                data_config=dict(
                    Ncams=6,
                    cams=[
                        'CAM_FRONT_LEFT',
                        'CAM_FRONT',
                        'CAM_FRONT_RIGHT',
                        'CAM_BACK_LEFT',
                        'CAM_BACK',
                        'CAM_BACK_RIGHT',
                    ],
                    crop_h=(
                        0.0,
                        0.0,
                    ),
                    flip=True,
                    input_size=(
                        256,
                        704,
                    ),
                    resize=(
                        -0.06,
                        0.11,
                    ),
                    resize_test=0.0,
                    rot=(
                        -5.4,
                        5.4,
                    ),
                    src_size=(
                        900,
                        1600,
                    )),
                is_train=True,
                sequential=False,
                type='PrepareImageInputs'),
            dict(
                bda_aug_conf=dict(
                    flip_dx_ratio=0.5,
                    flip_dy_ratio=0.5,
                    rot_lim=(
                        0,
                        0,
                    ),
                    scale_lim=(
                        1.0,
                        1.0,
                    )),
                classes=[
                    'others',
                    'barrier',
                    'bicycle',
                    'bus',
                    'car',
                    'construction_vehicle',
                    'motorcycle',
                    'pedestrian',
                    'traffic_cone',
                    'trailer',
                    'truck',
                    'driveable_surface',
                    'other_flat',
                    'sidewalk',
                    'terrain',
                    'manmade',
                    'vegetation',
                    'free',
                ],
                is_train=True,
                type='LoadAnnotationsBEVDepth'),
            dict(ignore_nonvisible=False, type='LoadOccGTFromFile'),
            dict(
                coord_type='LIDAR',
                load_dim=5,
                type='mmdet3d.LoadPointsFromFile',
                use_dim=5),
            dict(
                downsample=1,
                grid_config=dict(
                    dbound=[
                        1.0,
                        45.0,
                        0.5,
                    ],
                    xbound=[
                        -40,
                        40,
                        0.4,
                    ],
                    ybound=[
                        -40,
                        40,
                        0.4,
                    ],
                    zbound=[
                        -1,
                        5.4,
                        0.4,
                    ]),
                type='PointToMultiViewDepth'),
            dict(type='OccDefaultFormatBundle3D'),
            dict(
                keys=[
                    'img_inputs',
                    'gt_occ',
                ],
                meta_keys=[
                    'pc_range',
                    'occ_size',
                    'sample_idx',
                    'filename',
                ],
                type='CustomPack3DDetInputs'),
        ],
        test_mode=False,
        type='CustomNuScenesDatasetOccupancy'),
    num_workers=8,
    persistent_workers=True,
    sampler=dict(seed=0, shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(
        data_config=dict(
            Ncams=6,
            cams=[
                'CAM_FRONT_LEFT',
                'CAM_FRONT',
                'CAM_FRONT_RIGHT',
                'CAM_BACK_LEFT',
                'CAM_BACK',
                'CAM_BACK_RIGHT',
            ],
            crop_h=(
                0.0,
                0.0,
            ),
            flip=True,
            input_size=(
                256,
                704,
            ),
            resize=(
                -0.06,
                0.11,
            ),
            resize_test=0.0,
            rot=(
                -5.4,
                5.4,
            ),
            src_size=(
                900,
                1600,
            )),
        is_train=True,
        sequential=False,
        type='PrepareImageInputs'),
    dict(
        bda_aug_conf=dict(
            flip_dx_ratio=0.5,
            flip_dy_ratio=0.5,
            rot_lim=(
                0,
                0,
            ),
            scale_lim=(
                1.0,
                1.0,
            )),
        classes=[
            'others',
            'barrier',
            'bicycle',
            'bus',
            'car',
            'construction_vehicle',
            'motorcycle',
            'pedestrian',
            'traffic_cone',
            'trailer',
            'truck',
            'driveable_surface',
            'other_flat',
            'sidewalk',
            'terrain',
            'manmade',
            'vegetation',
            'free',
        ],
        is_train=True,
        type='LoadAnnotationsBEVDepth'),
    dict(ignore_nonvisible=False, type='LoadOccGTFromFile'),
    dict(
        coord_type='LIDAR',
        load_dim=5,
        type='mmdet3d.LoadPointsFromFile',
        use_dim=5),
    dict(
        downsample=1,
        grid_config=dict(
            dbound=[
                1.0,
                45.0,
                0.5,
            ],
            xbound=[
                -40,
                40,
                0.4,
            ],
            ybound=[
                -40,
                40,
                0.4,
            ],
            zbound=[
                -1,
                5.4,
                0.4,
            ]),
        type='PointToMultiViewDepth'),
    dict(type='OccDefaultFormatBundle3D'),
    dict(
        keys=[
            'img_inputs',
            'gt_occ',
        ],
        meta_keys=[
            'pc_range',
            'occ_size',
            'sample_idx',
            'filename',
        ],
        type='CustomPack3DDetInputs'),
]
val_cfg = dict()
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='bevdetv2-nuscenes_infos_val.pkl',
        classes=[
            'others',
            'barrier',
            'bicycle',
            'bus',
            'car',
            'construction_vehicle',
            'motorcycle',
            'pedestrian',
            'traffic_cone',
            'trailer',
            'truck',
            'driveable_surface',
            'other_flat',
            'sidewalk',
            'terrain',
            'manmade',
            'vegetation',
            'free',
        ],
        data_root='data/nuscenes/',
        filter_empty_gt=False,
        img_info_prototype='bevdet',
        modality=dict(
            use_camera=True,
            use_external=False,
            use_lidar=False,
            use_map=False,
            use_radar=False),
        occ_size=[
            200,
            200,
            16,
        ],
        pc_range=[
            -40.0,
            -40.0,
            -1,
            40.0,
            40.0,
            5.4,
        ],
        pipeline=[
            dict(
                data_config=dict(
                    Ncams=6,
                    cams=[
                        'CAM_FRONT_LEFT',
                        'CAM_FRONT',
                        'CAM_FRONT_RIGHT',
                        'CAM_BACK_LEFT',
                        'CAM_BACK',
                        'CAM_BACK_RIGHT',
                    ],
                    crop_h=(
                        0.0,
                        0.0,
                    ),
                    flip=True,
                    input_size=(
                        256,
                        704,
                    ),
                    resize=(
                        -0.06,
                        0.11,
                    ),
                    resize_test=0.0,
                    rot=(
                        -5.4,
                        5.4,
                    ),
                    src_size=(
                        900,
                        1600,
                    )),
                sequential=False,
                type='PrepareImageInputs'),
            dict(
                bda_aug_conf=dict(
                    flip_dx_ratio=0.5,
                    flip_dy_ratio=0.5,
                    rot_lim=(
                        0,
                        0,
                    ),
                    scale_lim=(
                        1.0,
                        1.0,
                    )),
                classes=[
                    'others',
                    'barrier',
                    'bicycle',
                    'bus',
                    'car',
                    'construction_vehicle',
                    'motorcycle',
                    'pedestrian',
                    'traffic_cone',
                    'trailer',
                    'truck',
                    'driveable_surface',
                    'other_flat',
                    'sidewalk',
                    'terrain',
                    'manmade',
                    'vegetation',
                    'free',
                ],
                is_train=False,
                type='LoadAnnotationsBEVDepth'),
            dict(
                coord_type='LIDAR',
                load_dim=5,
                type='mmdet3d.LoadPointsFromFile',
                use_dim=5),
            dict(type='OccDefaultFormatBundle3D'),
            dict(
                keys=[
                    'img_inputs',
                ],
                meta_keys=[
                    'pc_range',
                    'occ_size',
                    'sample_idx',
                    'filename',
                ],
                type='CustomPack3DDetInputs'),
        ],
        test_mode=True,
        type='CustomNuScenesDatasetOccupancy'),
    num_workers=8,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(type='CustomOccMetricNuscenes')
voxel_in_channels = [
    80,
    160,
    320,
    640,
]
voxel_out_channel = 48
voxel_out_channels = [
    48,
    96,
    192,
    384,
]
voxel_size = [
    0.4,
    0.4,
    0.4,
]
voxel_x = 0.4
voxel_y = 0.4
voxel_z = 0.4
work_dir = './work_dirs/sugocc_nus'
